coverage:
  status:
    project:
      default:  # disable the default status that measures entire project
        threshold: 5%
      tests:  # declare a new status context "tests"
        target: 100%  # we always want 100% coverage here
        paths: "travis/tests/"  # only include coverage in "travis/tests/" folder
