ignore:
  - "src/gen/"
coverage:
  status:
    project:
      src:
        target: auto
        paths: "src/"
      unittests:  # declare a new status context "unittests"
        target: 100%  # we always want 100% coverage here
        paths: "travis/unit_tests/"  # only include coverage in "travis/unit_tests" folder
