! Note that this file is automatically generated by build/mech_converter.py -- Any manual edits to this file will be overwritten when calling build/mech_converter.py

module mechanism_mod
    use, intrinsic :: iso_c_binding
    implicit none

contains

    subroutine update_p(p, q, t, TEMP, N2, O2, M, RH, H2O, BLHEIGHT, DEC, JFAC, DILUTE, ROOFOPEN, ASA, J, RO2) bind(c,name='update_p')

        use custom_functions_mod
        integer, parameter :: DP = selected_real_kind( p = 15, r = 307 )
        real(c_double), intent(inout) :: p(*), q(*)
        real(c_double), intent(in) :: t, TEMP, N2, O2, M, RH, H2O, BLHEIGHT, DEC, JFAC, DILUTE, ROOFOPEN, ASA, J(*), RO2
        !* Generic Rate Coefficients ;
!*;
q(1) = 2.7e-12_DP*EXP(360.0_DP/TEMP)  !KRO2NO = 2.7e-12_DP*EXP(360.0_DP/TEMP)
q(2) = 2.91e-13_DP*EXP(1300.0_DP/TEMP)  !KRO2HO2 = 2.91e-13_DP*EXP(1300.0_DP/TEMP)
q(3) = 5.2e-13_DP*EXP(980.0_DP/TEMP)  !KAPHO2 = 5.2e-13_DP*EXP(980.0_DP/TEMP)
q(4) = 7.5e-12_DP*EXP(290.0_DP/TEMP)  !KAPNO = 7.5e-12_DP*EXP(290.0_DP/TEMP)
q(5) = 2.3e-12_DP  !KRO2NO3 = 2.3e-12_DP
q(6) = 1.4e-12_DP*EXP(-1860_DP/TEMP)  !KNO3AL = 1.4e-12_DP*EXP(-1860_DP/TEMP)
q(7) = 1.00e+06_DP  !KDEC = 1.00e+06_DP
q(8) = 2.50e-14_DP*EXP(-300_DP/TEMP)  !KROPRIM = 2.50e-14_DP*EXP(-300_DP/TEMP)
q(9) = 2.50e-14_DP*EXP(-300_DP/TEMP)  !KROSEC = 2.50e-14_DP*EXP(-300_DP/TEMP)
q(10) = 1.03e-13_DP*EXP(365.0_DP/TEMP)  !KCH3O2 = 1.03e-13_DP*EXP(365.0_DP/TEMP)
q(11) = 3.5e-13_DP  !K298CH3O2 = 3.5e-13_DP
q(12) = 3.00e7_DP*EXP(-5300_DP/TEMP)  !K14ISOM1 = 3.00e7_DP*EXP(-5300_DP/TEMP)
!********************************************************************** ;
!*;
!* Complex reactions ;
!*;
q(13) = 1.10e-05_DP*M*EXP(-10100_DP/TEMP)  !KD0 = 1.10e-05_DP*M*EXP(-10100_DP/TEMP)
q(14) = 1.90e17_DP*EXP(-14100_DP/TEMP)  !KDI = 1.90e17_DP*EXP(-14100_DP/TEMP)
q(15) = q(13)/q(14)  !KRD = KD0/KDI
q(16) = 0.30_DP  !FCD = 0.30_DP
q(17) = 0.75_DP-1.27_DP*(LOG10(q(16)))  !NCD = 0.75_DP-1.27_DP*(LOG10(FCD))
q(18) = 10.0_DP**(LOG10(q(16))/(1.0_DP+(LOG10(q(15))/q(17))**2.0_DP))  !FD = 10.0_DP**(LOG10(FCD)/(1.0_DP+(LOG10(KRD)/NCD)**2.0_DP))
q(19) = (q(13)*q(14))*q(18)/(q(13)+q(14))  !KBPAN = (KD0*KDI)*FD/(KD0+KDI)
q(20) = 3.28e-28_DP*M*(TEMP/300_DP)**(-6.87_DP)  !KC0 = 3.28e-28_DP*M*(TEMP/300_DP)**(-6.87_DP)
q(21) = 1.125e-11_DP*(TEMP/300_DP)**(-1.105_DP)  !KCI = 1.125e-11_DP*(TEMP/300_DP)**(-1.105_DP)
q(22) = q(20)/q(21)  !KRC = KC0/KCI
q(23) = 0.30_DP  !FCC = 0.30_DP
q(24) = 0.75_DP-1.27_DP*(LOG10(q(23)))  !NC = 0.75_DP-1.27_DP*(LOG10(FCC))
q(25) = 10.0_DP**(LOG10(q(23))/(1.0_DP+(LOG10(q(22))/q(24))**2.0_DP))  !FC = 10.0_DP**(LOG10(FCC)/(1.0_DP+(LOG10(KRC)/NC)**2.0_DP))
q(26) = (q(20)*q(21))*q(25)/(q(20)+q(21))  !KFPAN = (KC0*KCI)*FC/(KC0+KCI)
q(27) = 1.0e-31_DP*M*(TEMP/300_DP)**(-1.6_DP)  !K10 = 1.0e-31_DP*M*(TEMP/300_DP)**(-1.6_DP)
q(28) = 5.0e-11_DP*(TEMP/300_DP)**(-0.3_DP)  !K1I = 5.0e-11_DP*(TEMP/300_DP)**(-0.3_DP)
q(29) = q(27)/q(28)  !KR1 = K10/K1I
q(30) = 0.85_DP  !FC1 = 0.85_DP
q(31) = 0.75_DP-1.27_DP*(LOG10(q(30)))  !NC1 = 0.75_DP-1.27_DP*(LOG10(FC1))
q(32) = 10.0_DP**(LOG10(q(30))/(1.0_DP+(LOG10(q(29))/q(31))**2.0_DP))  !F1 = 10.0_DP**(LOG10(FC1)/(1.0_DP+(LOG10(KR1)/NC1)**2.0_DP))
q(33) = (q(27)*q(28))*q(32)/(q(27)+q(28))  !KMT01 = (K10*K1I)*F1/(K10+K1I)
q(34) = 1.3e-31_DP*M*(TEMP/300_DP)**(-1.5_DP)  !K20 = 1.3e-31_DP*M*(TEMP/300_DP)**(-1.5_DP)
q(35) = 2.3e-11_DP*(TEMP/300_DP)**0.24_DP  !K2I = 2.3e-11_DP*(TEMP/300_DP)**0.24_DP
q(36) = q(34)/q(35)  !KR2 = K20/K2I
q(37) = 0.6_DP  !FC2 = 0.6_DP
q(38) = 0.75_DP-1.27_DP*(LOG10(q(37)))  !NC2 = 0.75_DP-1.27_DP*(LOG10(FC2))
q(39) = 10.0_DP**(LOG10(q(37))/(1.0_DP+(LOG10(q(36))/q(38))**2.0_DP))  !F2 = 10.0_DP**(LOG10(FC2)/(1.0_DP+(LOG10(KR2)/NC2)**2.0_DP))
q(40) = (q(34)*q(35))*q(39)/(q(34)+q(35))  !KMT02 = (K20*K2I)*F2/(K20+K2I)
q(41) = 3.6e-30_DP*M*(TEMP/300_DP)**(-4.1_DP)  !K30 = 3.6e-30_DP*M*(TEMP/300_DP)**(-4.1_DP)
q(42) = 1.9e-12_DP*(TEMP/300_DP)**0.2_DP  !K3I = 1.9e-12_DP*(TEMP/300_DP)**0.2_DP
q(43) = q(41)/q(42)  !KR3 = K30/K3I
q(44) = 0.35_DP  !FC3 = 0.35_DP
q(45) = 0.75_DP-1.27_DP*(LOG10(q(44)))  !NC3 = 0.75_DP-1.27_DP*(LOG10(FC3))
q(46) = 10.0_DP**(LOG10(q(44))/(1.0_DP+(LOG10(q(43))/q(45))**2.0_DP))  !F3 = 10.0_DP**(LOG10(FC3)/(1.0_DP+(LOG10(KR3)/NC3)**2.0_DP))
q(47) = (q(41)*q(42))*q(46)/(q(41)+q(42))  !KMT03 = (K30*K3I)*F3/(K30+K3I)
q(48) = 1.3e-3_DP*M*(TEMP/300_DP)**(-3.5_DP)*EXP(-11000_DP/TEMP)  !K40 = 1.3e-3_DP*M*(TEMP/300_DP)**(-3.5_DP)*EXP(-11000_DP/TEMP)
q(49) = 9.7e+14_DP*(TEMP/300_DP)**0.1_DP*EXP(-11080_DP/TEMP)  !K4I = 9.7e+14_DP*(TEMP/300_DP)**0.1_DP*EXP(-11080_DP/TEMP)
q(50) = q(48)/q(49)  !KR4 = K40/K4I
q(51) = 0.35_DP  !FC4 = 0.35_DP
q(52) = 0.75_DP-1.27_DP*(LOG10(q(51)))  !NC4 = 0.75_DP-1.27_DP*(LOG10(FC4))
q(53) = 10.0_DP**(LOG10(q(51))/(1.0_DP+(LOG10(q(50))/q(52))**2.0_DP))  !F4 = 10.0_DP**(LOG10(FC4)/(1.0_DP+(LOG10(KR4)/NC4)**2.0_DP))
q(54) = (q(48)*q(49))*q(53)/(q(48)+q(49))  !KMT04 = (K40*K4I)*F4/(K40+K4I)
q(55) = 1.44e-13_DP*(1.0_DP+(M/4.2e+19_DP))  !KMT05 = 1.44e-13_DP*(1.0_DP+(M/4.2e+19_DP))
q(56) = 1.0_DP + (1.40e-21_DP*EXP(2200.0_DP/TEMP)*H2O)  !KMT06 = 1.0_DP + (1.40e-21_DP*EXP(2200.0_DP/TEMP)*H2O)
q(57) = 7.4e-31_DP*M*(TEMP/300_DP)**(-2.4_DP)  !K70 = 7.4e-31_DP*M*(TEMP/300_DP)**(-2.4_DP)
q(58) = 3.3e-11_DP*(TEMP/300_DP)**(-0.3_DP)  !K7I = 3.3e-11_DP*(TEMP/300_DP)**(-0.3_DP)
q(59) = q(57)/q(58)  !KR7 = K70/K7I
q(60) = 0.81_DP  !FC7 = 0.81_DP
q(61) = 0.75_DP-1.27_DP*(LOG10(q(60)))  !NC7 = 0.75_DP-1.27_DP*(LOG10(FC7))
q(62) = 10.0_DP**(LOG10(q(60))/(1.0_DP+(LOG10(q(59))/q(61))**2.0_DP))  !F7 = 10.0_DP**(LOG10(FC7)/(1.0_DP+(LOG10(KR7)/NC7)**2.0_DP))
q(63) = (q(57)*q(58))*q(62)/(q(57)+q(58))  !KMT07 = (K70*K7I)*F7/(K70+K7I)
q(64) = 3.2e-30_DP*M*(TEMP/300_DP)**(-4.5_DP)  !K80 = 3.2e-30_DP*M*(TEMP/300_DP)**(-4.5_DP)
q(65) = 3.0e-11_DP  !K8I = 3.0e-11_DP
q(66) = q(64)/q(65)  !KR8 = K80/K8I
q(67) = 0.41_DP  !FC8 = 0.41_DP
q(68) = 0.75_DP-1.27_DP*(LOG10(q(67)))  !NC8 = 0.75_DP-1.27_DP*(LOG10(FC8))
q(69) = 10.0_DP**(LOG10(q(67))/(1.0_DP+(LOG10(q(66))/q(68))**2.0_DP))  !F8 = 10.0_DP**(LOG10(FC8)/(1.0_DP+(LOG10(KR8)/NC8)**2.0_DP))
q(70) = (q(64)*q(65))*q(69)/(q(64)+q(65))  !KMT08 = (K80*K8I)*F8/(K80+K8I)
q(71) = 1.4e-31_DP*M*(TEMP/300_DP)**(-3.1_DP)  !K90 = 1.4e-31_DP*M*(TEMP/300_DP)**(-3.1_DP)
q(72) = 4.0e-12_DP  !K9I = 4.0e-12_DP
q(73) = q(71)/q(72)  !KR9 = K90/K9I
q(74) = 0.4_DP  !FC9 = 0.4_DP
q(75) = 0.75_DP-1.27_DP*(LOG10(q(74)))  !NC9 = 0.75_DP-1.27_DP*(LOG10(FC9))
q(76) = 10.0_DP**(LOG10(q(74))/(1.0_DP+(LOG10(q(73))/q(75))**2.0_DP))  !F9 = 10.0_DP**(LOG10(FC9)/(1.0_DP+(LOG10(KR9)/NC9)**2.0_DP))
q(77) = (q(71)*q(72))*q(76)/(q(71)+q(72))  !KMT09 = (K90*K9I)*F9/(K90+K9I)
q(78) = 4.10e-05_DP*M*EXP(-10650_DP/TEMP)  !K100 = 4.10e-05_DP*M*EXP(-10650_DP/TEMP)
q(79) = 6.0e+15_DP*EXP(-11170_DP/TEMP)  !K10I = 6.0e+15_DP*EXP(-11170_DP/TEMP)
q(80) = q(78)/q(79)  !KR10 = K100/K10I
q(81) = 0.4_DP  !FC10 = 0.4_DP
q(82) = 0.75_DP-1.27_DP*(LOG10(q(81)))  !NC10 = 0.75_DP-1.27_DP*(LOG10(FC10))
q(83) = 10.0_DP**(LOG10(q(81))/(1.0_DP+(LOG10(q(80))/q(82))**2.0_DP))  !F10 = 10.0_DP**(LOG10(FC10)/(1.0_DP+(LOG10(KR10)/NC10)**2.0_DP))
q(84) = (q(78)*q(79))*q(83)/(q(78)+q(79))  !KMT10 = (K100*K10I)*F10/(K100+K10I)
q(85) = 2.40e-14_DP*EXP(460.0_DP/TEMP)  !K1 = 2.40e-14_DP*EXP(460.0_DP/TEMP)
q(86) = 6.50e-34_DP*EXP(1335.0_DP/TEMP)  !K3 = 6.50e-34_DP*EXP(1335.0_DP/TEMP)
q(87) = 2.70e-17_DP*EXP(2199.0_DP/TEMP)  !K4 = 2.70e-17_DP*EXP(2199.0_DP/TEMP)
q(88) = (q(86)*M)/(1.0_DP+(q(86)*M/q(87)))  !K2 = (K3*M)/(1.0_DP+(K3*M/K4))
q(89) = q(85) + q(88)  !KMT11 = K1 + K2
q(90) = 2.5e-31_DP*M*(TEMP/300_DP)**(-2.6_DP)  !K120 = 2.5e-31_DP*M*(TEMP/300_DP)**(-2.6_DP)
q(91) = 2.0e-12_DP  !K12I = 2.0e-12_DP
q(92) = q(90)/q(91)  !KR12 = K120/K12I
q(93) = 0.53_DP  !FC12 = 0.53_DP
q(94) = 0.75_DP-1.27_DP*(LOG10(q(93)))  !NC12 = 0.75_DP-1.27_DP*(LOG10(FC12))
q(95) = 10.0_DP**(LOG10(q(93))/(1.0_DP+(LOG10(q(92))/q(94))**2.0_DP))  !F12 = 10.0_DP**(LOG10(FC12)/(1.0_DP+(LOG10(KR12)/NC12)**2.0_DP))
q(96) = (q(90)*q(91)*q(95))/(q(90)+q(91))  !KMT12 = (K120*K12I*F12)/(K120+K12I)
q(97) = 2.5e-30_DP*M*(TEMP/300_DP)**(-5.5_DP)  !K130 = 2.5e-30_DP*M*(TEMP/300_DP)**(-5.5_DP)
q(98) = 1.8e-11_DP  !K13I = 1.8e-11_DP
q(99) = q(97)/q(98)  !KR13 = K130/K13I
q(100) = 0.36_DP  !FC13 = 0.36_DP
q(101) = 0.75_DP-1.27_DP*(LOG10(q(100)))  !NC13 = 0.75_DP-1.27_DP*(LOG10(FC13))
q(102) = 10.0_DP**(LOG10(q(100))/(1.0_DP+(LOG10(q(99))/q(101))**2.0_DP))  !F13 = 10.0_DP**(LOG10(FC13)/(1.0_DP+(LOG10(KR13)/NC13)**2.0_DP))
q(103) = (q(97)*q(98))*q(102)/(q(97)+q(98))  !KMT13 = (K130*K13I)*F13/(K130+K13I)
q(104) = 9.0e-5_DP*EXP(-9690_DP/TEMP)*M  !K140 = 9.0e-5_DP*EXP(-9690_DP/TEMP)*M
q(105) = 1.1e+16_DP*EXP(-10560_DP/TEMP)  !K14I = 1.1e+16_DP*EXP(-10560_DP/TEMP)
q(106) = q(104)/q(105)  !KR14 = K140/K14I
q(107) = 0.36_DP  !FC14 = 0.36_DP
q(108) = 0.75_DP-1.27_DP*(LOG10(q(107)))  !NC14 = 0.75_DP-1.27_DP*(LOG10(FC14))
q(109) = 10.0_DP**(LOG10(q(107))/(1.0_DP+(LOG10(q(106))/q(108))**2.0_DP))  !F14 = 10.0_DP**(LOG10(FC14)/(1.0_DP+(LOG10(KR14)/NC14)**2.0_DP))
q(110) = (q(104)*q(105))*q(109)/(q(104)+q(105))  !KMT14 = (K140*K14I)*F14/(K140+K14I)
q(111) = 8.6e-29_DP*M*(TEMP/300_DP)**(-3.1_DP)  !K150 = 8.6e-29_DP*M*(TEMP/300_DP)**(-3.1_DP)
q(112) = 9.0e-12_DP*(TEMP/300_DP)**(-0.85_DP)  !K15I = 9.0e-12_DP*(TEMP/300_DP)**(-0.85_DP)
q(113) = q(111)/q(112)  !KR15 = K150/K15I
q(114) = 0.48_DP  !FC15 = 0.48_DP
q(115) = 0.75_DP-1.27_DP*(LOG10(q(114)))  !NC15 = 0.75_DP-1.27_DP*(LOG10(FC15))
q(116) = 10.0_DP**(LOG10(q(114))/(1.0_DP+(LOG10(q(113))/q(115))**2.0_DP))  !F15 = 10.0_DP**(LOG10(FC15)/(1.0_DP+(LOG10(KR15)/NC15)**2.0_DP))
q(117) = (q(111)*q(112))*q(116)/(q(111)+q(112))  !KMT15 = (K150*K15I)*F15/(K150+K15I)
q(118) = 8e-27_DP*M*(TEMP/300_DP)**(-3.5_DP)  !K160 = 8e-27_DP*M*(TEMP/300_DP)**(-3.5_DP)
q(119) = 3.0e-11_DP*(TEMP/300_DP)**(-1_DP)  !K16I = 3.0e-11_DP*(TEMP/300_DP)**(-1_DP)
q(120) = q(118)/q(119)  !KR16 = K160/K16I
q(121) = 0.5_DP  !FC16 = 0.5_DP
q(122) = 0.75_DP-1.27_DP*(LOG10(q(121)))  !NC16 = 0.75_DP-1.27_DP*(LOG10(FC16))
q(123) = 10.0_DP**(LOG10(q(121))/(1.0_DP+(LOG10(q(120))/q(122))**2.0_DP))  !F16 = 10.0_DP**(LOG10(FC16)/(1.0_DP+(LOG10(KR16)/NC16)**2.0_DP))
q(124) = (q(118)*q(119))*q(123)/(q(118)+q(119))  !KMT16 = (K160*K16I)*F16/(K160+K16I)
q(125) = 5.0e-30_DP*M*(TEMP/300_DP)**(-1.5_DP)  !K170 = 5.0e-30_DP*M*(TEMP/300_DP)**(-1.5_DP)
q(126) = 1.0e-12_DP  !K17I = 1.0e-12_DP
q(127) = q(125)/q(126)  !KR17 = K170/K17I
q(128) = 0.17_DP*EXP(-51_DP/TEMP)+EXP(-TEMP/204_DP)  !FC17 = 0.17_DP*EXP(-51_DP/TEMP)+EXP(-TEMP/204_DP)
q(129) = 0.75_DP-1.27_DP*(LOG10(q(128)))  !NC17 = 0.75_DP-1.27_DP*(LOG10(FC17))
q(130) = 10.0_DP**(LOG10(q(128))/(1.0_DP+(LOG10(q(127))/q(129))**2.0_DP))  !F17 = 10.0_DP**(LOG10(FC17)/(1.0_DP+(LOG10(KR17)/NC17)**2.0_DP))
q(131) = (q(125)*q(126)*q(130))/(q(125)+q(126))  !KMT17 = (K170*K17I*F17)/(K170+K17I)
q(132) = 9.5e-39_DP*O2*EXP(5270.0_DP/TEMP)/(1.0_DP+7.5e-29_DP*O2*EXP(5610.0_DP/TEMP))  !KMT18 = 9.5e-39_DP*O2*EXP(5270.0_DP/TEMP)/(1.0_DP+7.5e-29_DP*O2*EXP(5610.0_DP/TEMP))
q(133) = 1.7e-03_DP*EXP(-11280_DP/TEMP)*M  !KPPN0 = 1.7e-03_DP*EXP(-11280_DP/TEMP)*M
q(134) = 8.3e+16_DP*EXP(-13940_DP/TEMP)  !KPPNI = 8.3e+16_DP*EXP(-13940_DP/TEMP)
q(135) = q(133)/q(134)  !KRPPN = KPPN0/KPPNI
q(136) = 0.36_DP  !FCPPN = 0.36_DP
q(137) = 0.75_DP-1.27_DP*(LOG10(q(136)))  !NCPPN = 0.75_DP-1.27_DP*(LOG10(FCPPN))
q(138) = 10.0_DP**(LOG10(q(136))/(1.0_DP+(LOG10(q(135))/q(137))**2.0_DP))  !FPPN = 10.0_DP**(LOG10(FCPPN)/(1.0_DP+(LOG10(KRPPN)/NCPPN)**2.0_DP))
q(139) = (q(133)*q(134))*q(136)/(q(133)+q(134))  !KBPPN = (KPPN0*KPPNI)*FCPPN/(KPPN0+KPPNI)
!****************************************************** ;
!*;
!* Reaction definitions. ;
!*;
p(1) = 5.6D-34*N2*(TEMP/300)**(-2.6)*O2   !% 5.6D-34*N2*(TEMP/300)@-2.6*O2 : O = O3 ;
p(2) = 6.0D-34*O2*(TEMP/300)**(-2.6)*O2   !% 6.0D-34*O2*(TEMP/300)@-2.6*O2 : O = O3 ;
p(3) = 8.0D-12*EXP(-2060/TEMP)   !% 8.0D-12*EXP(-2060/TEMP) : O + O3 = ;
p(4) = q(33)   !% KMT01 : O + NO = NO2 ;
p(5) = 5.5D-12*EXP(188/TEMP)   !% 5.5D-12*EXP(188/TEMP) : O + NO2 = NO ;
p(6) = q(40)   !% KMT02 : O + NO2 = NO3 ;
p(7) = 3.2D-11*EXP(67/TEMP)*O2   !% 3.2D-11*EXP(67/TEMP)*O2 : O1D = O ;
p(8) = 2.0D-11*EXP(130/TEMP)*N2   !% 2.0D-11*EXP(130/TEMP)*N2 : O1D = O ;
p(9) = 1.4D-12*EXP(-1310/TEMP)   !% 1.4D-12*EXP(-1310/TEMP) : NO + O3 = NO2 ;
p(10) = 1.4D-13*EXP(-2470/TEMP)   !% 1.4D-13*EXP(-2470/TEMP) : NO2 + O3 = NO3 ;
p(11) = 3.3D-39*EXP(530/TEMP)*O2   !% 3.3D-39*EXP(530/TEMP)*O2 : NO + NO = NO2 + NO2 ;
p(12) = 1.8D-11*EXP(110/TEMP)   !% 1.8D-11*EXP(110/TEMP) : NO + NO3 = NO2 + NO2 ;
p(13) = 4.50D-14*EXP(-1260/TEMP)   !% 4.50D-14*EXP(-1260/TEMP) : NO2 + NO3 = NO + NO2 ;
p(14) = q(47)   !% KMT03 : NO2 + NO3 = N2O5 ;
p(15) = 2.14D-10*H2O   !% 2.14D-10*H2O : O1D = OH + OH ;
p(16) = 1.70D-12*EXP(-940/TEMP)   !% 1.70D-12*EXP(-940/TEMP) : OH + O3 = HO2 ;
p(17) = 7.7D-12*EXP(-2100/TEMP)   !% 7.7D-12*EXP(-2100/TEMP) : OH + H2 = HO2 ;
p(18) = q(55)   !% KMT05 : OH + CO = HO2 ;
p(19) = 2.9D-12*EXP(-160/TEMP)   !% 2.9D-12*EXP(-160/TEMP) : OH + H2O2 = HO2 ;
p(20) = 2.03D-16*(TEMP/300)**4.57*EXP(693/TEMP)   !% 2.03D-16*(TEMP/300)@4.57*EXP(693/TEMP) : HO2 + O3 = OH ;
p(21) = 4.8D-11*EXP(250/TEMP)   !% 4.8D-11*EXP(250/TEMP) : OH + HO2 = ;
p(22) = 2.20D-13*q(56)*EXP(600/TEMP)   !% 2.20D-13*KMT06*EXP(600/TEMP) : HO2 + HO2 = H2O2 ;
p(23) = 1.90D-33*M*q(56)*EXP(980/TEMP)   !% 1.90D-33*M*KMT06*EXP(980/TEMP) : HO2 + HO2 = H2O2 ;
p(24) = q(63)   !% KMT07 : OH + NO = HONO ;
p(25) = q(70)   !% KMT08 : OH + NO2 = HNO3 ;
p(26) = 2.0D-11   !% 2.0D-11 : OH + NO3 = HO2 + NO2 ;
p(27) = 3.45D-12*EXP(270/TEMP)   !% 3.45D-12*EXP(270/TEMP) : HO2 + NO = OH + NO2 ;
p(28) = q(77)   !% KMT09 : HO2 + NO2 = HO2NO2 ;
p(29) = 3.2D-13*EXP(690/TEMP)*1.0   !% 3.2D-13*EXP(690/TEMP)*1.0 : OH + HO2NO2 = NO2 ;
p(30) = 4.0D-12   !% 4.0D-12 : HO2 + NO3 = OH + NO2 ;
p(31) = 2.5D-12*EXP(260/TEMP)   !% 2.5D-12*EXP(260/TEMP) : OH + HONO = NO2 ;
p(32) = q(89)   !% KMT11 : OH + HNO3 = NO3 ;
p(33) = 4.0D-32*EXP(-1000/TEMP)*M   !% 4.0D-32*EXP(-1000/TEMP)*M : O + SO2 = SO3 ;
p(34) = q(96)   !% KMT12 : OH + SO2 = HSO3 ;
p(35) = 1.3D-12*EXP(-330/TEMP)*O2   !% 1.3D-12*EXP(-330/TEMP)*O2 : HSO3 = HO2 + SO3 ;
p(36) = 6.00D-06   !% 6.00D-06 : HNO3 = NA ;
p(37) = 4.00D-04   !% 4.00D-04 : N2O5 = NA + NA ;
p(38) = 1.20D-15*H2O   !% 1.20D-15*H2O : SO3 = SA ;
p(39) = J(1)   !% J<1> : O3 = O1D ;
p(40) = J(2)   !% J<2> : O3 = O ;
p(41) = J(3)   !% J<3> : H2O2 = OH + OH ;
p(42) = J(4)   !% J<4> : NO2 = NO + O ;
p(43) = J(5)   !% J<5> : NO3 = NO ;
p(44) = J(6)   !% J<6> : NO3 = NO2 + O ;
p(45) = J(7)   !% J<7> : HONO = OH + NO ;
p(46) = J(8)   !% J<8> : HNO3 = OH + NO2 ;
p(47) = q(54)   !% KMT04 : N2O5 = NO2 + NO3 ;
p(48) = q(84)   !% KMT10 : HO2NO2 = HO2 + NO2 ;
p(49) = 6.6D-12*EXP(-1240/TEMP)   !% 6.6D-12*EXP(-1240/TEMP) : CL + CH4 = CH3O2 ;
p(50) = 1.85D-12*EXP(-1690/TEMP)   !% 1.85D-12*EXP(-1690/TEMP) : OH + CH4 = CH3O2 ;
p(51) = 3.8D-13*EXP(780/TEMP)*(1-1/(1+498*EXP(-1160/TEMP)))   !% 3.8D-13*EXP(780/TEMP)*(1-1/(1+498*EXP(-1160/TEMP))) : CH3O2 + HO2 = CH3OOH ;
p(52) = 3.8D-13*EXP(780/TEMP)*(1/(1+498*EXP(-1160/TEMP)))   !% 3.8D-13*EXP(780/TEMP)*(1/(1+498*EXP(-1160/TEMP))) : CH3O2 + HO2 = HCHO ;
p(53) = 2.3D-12*EXP(360/TEMP)*0.001   !% 2.3D-12*EXP(360/TEMP)*0.001 : CH3O2 + NO = CH3NO3 ;
p(54) = 2.3D-12*EXP(360/TEMP)*0.999   !% 2.3D-12*EXP(360/TEMP)*0.999 : CH3O2 + NO = CH3O + NO2 ;
p(55) = q(103)   !% KMT13 : CH3O2 + NO2 = CH3O2NO2 ;
p(56) = 1.2D-12   !% 1.2D-12 : CH3O2 + NO3 = CH3O + NO2 ;
p(57) = 2*q(10)*RO2*7.18*EXP(-885/TEMP)   !% 2*KCH3O2*RO2*7.18*EXP(-885/TEMP) : CH3O2 = CH3O ;
p(58) = 2*q(10)*RO2*0.5*(1-7.18*EXP(-885/TEMP))   !% 2*KCH3O2*RO2*0.5*(1-7.18*EXP(-885/TEMP)) : CH3O2 = CH3OH ;
p(59) = 2*q(10)*RO2*0.5*(1-7.18*EXP(-885/TEMP))   !% 2*KCH3O2*RO2*0.5*(1-7.18*EXP(-885/TEMP)) : CH3O2 = HCHO ;
p(60) = J(41)   !% J<41> : CH3OOH = CH3O + OH ;
p(61) = 5.3D-12*EXP(190/TEMP)*0.6   !% 5.3D-12*EXP(190/TEMP)*0.6 : OH + CH3OOH = CH3O2 ;
p(62) = 5.3D-12*EXP(190/TEMP)*0.4   !% 5.3D-12*EXP(190/TEMP)*0.4 : OH + CH3OOH = HCHO + OH ;
p(63) = J(11)   !% J<11> : HCHO = CO + HO2 + HO2 ;
p(64) = J(12)   !% J<12> : HCHO = H2 + CO ;
p(65) = 5.5D-16   !% 5.5D-16 : NO3 + HCHO = HNO3 + CO + HO2 ;
p(66) = 5.4D-12*EXP(135/TEMP)   !% 5.4D-12*EXP(135/TEMP) : OH + HCHO = HO2 + CO ;
p(67) = J(51)   !% J<51> : CH3NO3 = CH3O + NO2 ;
p(68) = 4.0D-13*EXP(-845/TEMP)   !% 4.0D-13*EXP(-845/TEMP) : OH + CH3NO3 = HCHO + NO2 ;
p(69) = 7.2D-14*EXP(-1080/TEMP)*O2   !% 7.2D-14*EXP(-1080/TEMP)*O2 : CH3O = HCHO + HO2 ;
p(70) = q(110)   !% KMT14 : CH3O2NO2 = CH3O2 + NO2 ;
p(71) = 2.85D-12*EXP(-345/TEMP)   !% 2.85D-12*EXP(-345/TEMP) : CH3OH + OH = HO2 + HCHO ;
!*;
!* End of Subset.  No. of Species = 30, No. of Reactions = 71 ;

    end subroutine update_p
end module mechanism_mod
