#!/bin/sh

curl -O https://s3-us-west-2.amazonaws.com/atchem/travis-cache/homebrew-cache.tar.gz
if [ -f homebrew-cache.tar.gz ]; then
  if ! tar tf homebrew-cache.tar.gz &>/dev/null; then
    rm homebrew-cache.tar.gz
    exit 0
  fi
  tar zxf homebrew-cache.tar.gz --directory /usr/local/Cellar
  brew link isl@0.12 cloog gcc@4.8 gettext homebrew/science/numdiff
fi
