# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # ubuntu only
      - name: Run on ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: echo Running on a Linux machine ${{ matrix.os }}
        
      - name: which gfortran
        if: matrix.os == 'ubuntu-latest'
        run: which gfortran
          
      - name: gfortran version
        if: matrix.os == 'ubuntu-latest'
        run: gfortran --version

      - name: install liblapack-dev
        if: matrix.os == 'ubuntu-latest'
        run: apt-get install liblapack-dev
      
      # macOS only
      - name: Run on macOS
        if: matrix.os == 'macos-latest'
        run: echo Running on a macOS ${{ matrix.os }}
      
      - name: which gfortran (macOS)
        if: matrix.os == 'macos-latest'
        run: which gfortran
      
      - name: gfortran version (macOS)
        if: matrix.os == 'macos-latest'
        run: gfortran --version
      
      - name: Install gettext
        if: matrix.os == 'macos-latest'
        run: brew install gettext
      
      # both OSs
      - name: Install cvode
        run: ./tools/install/install_cvode.sh $PWD /usr/bin/gfortran
      
      - name: Install openlibm
        run: ./tools/install/install_openlibm.sh $PWD
      
      - name: Install numdiff
        run: ./tools/install/install_numdiff.sh $PWD ; export PATH=$PATH:$PWD/numdiff/bin
      
      - name: Install fruit
        run: ./tools/install/install_fruit.sh $PWD

      